apptrack/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'apptrack.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tracker/', include('tracker.urls')),
    url(r'^hangman/', include('hangman.urls')),
    url(r'^$', include('resume.urls')),
    url(r'^guestbook/', include('guestbook.urls')),
)

resume/urls.py
__author__ = 'rebecca'

from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
                       url(r'^$', views.resume, name='resume'),
    )

tracker/urls.py
__author__ = 'rebecca'

from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^addapp/$', views.addapp, name='addapp'),
                       url(r'^user/(?P<username>[\w\.\-\+_@]+)/$', views.apps, name='apps'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^login/$', views.user_login, name='login'),
                       url(r'^logout/$', views.user_logout, name='logout'),
                       url(r'^delete/(?P<app_id>\w+)/$', views.delete, name='delete'),
                       url(r'^edit/(?P<app_id>\w+)/$', views.edit, name='edit'),
    )

tracker/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.


class Application(models.Model):

    user = models.ForeignKey(User)

    title = models.CharField(max_length=64)
    description = models.CharField(max_length=140)
    company = models.CharField(max_length=64)
    submitted_date = models.DateField(default=date.today())

    created_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'{0}'.format(self.title)


class Interview(models.Model):

    app = models.ForeignKey(Application)

    scheduled_datetime = models.DateTimeField()

    contact_number = models.CharField(max_length=24, blank=True)
    contact_name = models.CharField(max_length = 32, blank=True)
    contact_email = models.EmailField(blank=True)

    thankyou_note_yesno = models.BooleanField()

    notes = models.TextField(max_length=256, blank=True)

    created_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):

        return u'Interview with {0} on {1}'.format(self.contact_name, self.scheduled_datetime)

tracker/forms.py
__author__ = 'rebecca'

from django import forms
from models import Application, Interview


class ApplicationForm(forms.ModelForm):

    class Meta:
        model = Application
        fields = ('title', 'description', 'company', 'submitted_date')


class InterviewForm(forms.ModelForm):

    class Meta:
        model = Interview
        fields = ('scheduled_datetime', 'contact_name', 'contact_number', 'contact_email', 'thankyou_note_yesno',
                  'notes')

tracker/views.py
from datetime import datetime, timedelta
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from models import Application
from forms import ApplicationForm


# Create your views here.


def index(request):

    return render(request, 'tracker/index.html')


def apps(request, username):

    user = User.objects.get(username=username)

    if request.user == user:

        application_list = Application.objects.filter(user=user).order_by('title')

        past_applications = len(Application.objects.filter(user=user).filter(submitted_date__gte=datetime.today()-timedelta(days=30)))

        content = { 'applications': application_list, 'past_apps': past_applications, 'username': username }

        return render(request, 'tracker/apps.html', content)

    else:

        return HttpResponseRedirect('/tracker/')


@login_required(login_url='/tracker/login/')
def addapp(request):

    if request.method == 'POST':

        app = Application(user=request.user)

        form = ApplicationForm(request.POST, instance=app)

        if form.is_valid():
            form.save(commit=True)

            return HttpResponseRedirect('/tracker/user/{0}/'.format(request.user.username))

        else:
            print form.errors

    else:

        form = ApplicationForm()

    content = { 'form': form }

    return render(request, 'tracker/addapp.html', content)


def register(request):
    if request.method == 'POST':

        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            username = request.POST['username']
            password = request.POST['password1']

            user = authenticate(username=username, password=password)

            login(request, user)

            return HttpResponseRedirect('/tracker/')

        else:
            print form.errors

    else:

        form = UserCreationForm()

    content = { 'form': form }

    return render(request, 'tracker/register.html', content)


def user_login(request):
    if request.method == 'POST':

        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/tracker/')
                else:
                    return HttpResponse('Your account is currently disabled.')

        else:
            print form.errors

    else:
        form = AuthenticationForm()

    content = { 'form': form }

    return render(request, 'tracker/login.html', content)


@login_required(login_url='/tracker/login/')
def user_logout(request):
    logout(request)

    return HttpResponseRedirect('/tracker/')


@login_required(login_url='/tracker/login/')
def delete(request, app_id):
    if request.method == 'POST':
        user = request.user

        app = Application.objects.get(pk=app_id)

        if app.user == user:

            app.delete()

            return HttpResponseRedirect('/tracker/user/{0}/'.format(user.username))

        else:

            return HttpResponse('User mismatch, application not deleted.')

    else:
        return HttpResponseRedirect('/tracker/')


@login_required(login_url='/tracker/login/')
def edit(request, app_id):

    user = request.user
    app = Application.objects.get(pk=app_id)

    if app.user == user:

        form = ApplicationForm(request.POST or None, instance=app)

        if request.method == 'POST':

            if form.is_valid():

                obj = form.save(commit=False)

                obj.save()

                return HttpResponseRedirect('/tracker/user/{0}/'.format(user.username))

            else:

                print form.errors

        else:

            form = ApplicationForm(instance=app)

    else:
        return HttpResponse('User mismatch, permission denied.')

    content = { 'form': form, 'app': app }

    return render(request, 'tracker/edit.html', content)

templates/tracker/addapp.html
{% extends 'tracker/base.html' %}

{% load widget_tweaks %}

{% block head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css">
{% endblock %}

{% block title %}
Add Tracker Application
{% endblock %}

{% block content %}

<h1>Add Tracker Application</h1>

<form role='form' class='form-horizontal' action="/tracker/addapp/" id="application_form" method="post">

	{% csrf_token %}

	{% for field in form %}
	<div class="form-group">
		<div class="col-sm-10 {% if field.errors %} has-error {% endif %}">
		{% render_field field placeholder=field.label class='form-control' %}
		{% if field.errors %}
		<span class="help-block">{{ field.errors.as_text }}</span>
		{% endif %}
		</div>
	</div>
	{% endfor %}

	<button type="submit" name="submit" class='btn btn-default'>Add Application</button>

</form>

{% endblock %}

{% block scripts %}

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
	
	// Datepicker configuration
	$('#id_submitted_date').datepicker({
		format: 'yyyy-mm-dd',
		todayHighlight: true,
		endDate: '0d'
	})

</script>

{% endblock %}

templates/tracker/apps.html
{% extends 'tracker/base.html' %}

{% block head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.css">
{% endblock %}

{% block title %}
Tracker Application List
{% endblock %}

{% block content %}

<h1>Tracker Application List</h1>


<h5 class='text-right'>You have submitted <span class="label label-default">{{ past_apps }}</span> applications in the past 30 days.</h5>

<table class='table'>
<tr>
<th class='col-md-2'>Job Title</th>
<th class='col-md-6'>Job Description</th>
<th class='col-md-2'>Company</th>
<th class='col-md-1'>Date Applied</th>
{% if user.is_authenticated %}<th class='col-md-1'></th> {% endif %}
</tr>
{% for application in applications %}
<tr>
<td class='col-md-2'>{{ application.title }}</td>
<td class='col-md-6'>{{ application.description }}</td>
<td class='col-md-2'>{{ application.company }}</td>
<td class='col-md-1'>{{ application.submitted_date }}</td>
<td class='col-md-1'>
	<form action="/tracker/delete/{{ application.id }}/" id="delete_form" role="form" method="POST">
		{% csrf_token %}
		<button type="submit" name="delete" class="btn btn-link"><span class="glyphicon glyphicon-remove"></span></button>
		<a href="/tracker/edit/{{ application.id }}/"><span class="glyphicon glyphicon-pencil"></span></a>
	</form>
</td>
</tr>
{% endfor %}
</table>

<div class="container">
<a href="/tracker/addapp/" role="button" class="btn btn-primary btn-lg active btn-block">Add an Application</a>
</div>

{% endblock %}

templates/tracker/base.html
<!DOCTYPE html>
<html>
<head>

    <title>{% block title %}{% endblock %}</title>

	<link rel="stylesheet" href="http://bootswatch.com/cerulean/bootstrap.min.css" type="text/css">

    {% block head %}
    {% endblock %}

</head>
<body>


<nav class="navbar navbar-default navbar-static-top" role="navigation">
	<div class="container-fluid">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="/tracker/">Home</a></li>
			{% if user.is_authenticated %}
				<li><a href="/tracker/user/{{ user.username }}/">My Apps</a></li>
				<li><a href="/tracker/logout/">Logout</a></li>
			{% else %}
				<li><a href="/tracker/login/">Login</a></li>
				<li><a href="/tracker/register/">Register an Account</a></li>
			{% endif %}
		</ul>
	</div>

</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

	{% block scripts %}
	{% endblock %}

</body>
</html>

templates/tracker/edit.html
{% extends 'tracker/base.html' %}

{% load widget_tweaks %}

{% block head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker3.min.css">
{% endblock %}

{% block title %}
Edit Tracker Application
{% endblock %}

{% block content %}

<h1>Edit Tracker Application</h1>

<form role='form' class='form-horizontal' action="/tracker/edit/{{ app.id }}/" id="edit_application_form" method="post">

	{% csrf_token %}

	{% for field in form %}
	<div class="form-group">
		<div class="col-sm-10 {% if field.errors %} has-error {% endif %}">
		{% render_field field placeholder=field.label class='form-control' %}
		{% if field.errors %}
		<span class="help-block">{{ field.errors.as_text }}</span>
		{% endif %}
		</div>
	</div>
	{% endfor %}

	<button type="submit" name="submit" class='btn btn-default'>Edit Application</button>

</form>

{% endblock %}

{% block scripts %}

<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

<script type="text/javascript">
	
	// Datepicker configuration
	$('#id_submitted_date').datepicker({
		format: 'yyyy-mm-dd',
		todayHighlight: true,
		endDate: '0d'
	})

</script>

{% endblock %}

templates/tracker/index.html
{% extends 'tracker/base.html' %}

{% block title %}
Tracker Index Page
{% endblock %}

{% block content %}

<div class="jumbotron">
{% if user.is_authenticated %}
	<h1>Welcome, {{ user.username }}.</h1>
{% else %}
	<h1>Welcome.</h1>
{% endif %}
	<p>This service allows you to track job applications you have submitted.</p>
{% if user.is_authenticated %}
	<a href="/tracker/user/{{ user.username }}/" role="button" class="btn btn-primary btn-lg active btn-block">Go look at your applications!</a>
{% else %}
	<a href="/tracker/register/" role="button" class="btn btn-primary btn-lg active btn-block">Sign up to track your applications!</a>
{% endif %}
</div>
{% endblock %}

templates/tracker/login.html
{% extends 'tracker/base.html' %}

{% load widget_tweaks %}

{% block title %}
User Login
{% endblock %}

{% block content %}

<h1>User Login</h1>

<form action="/tracker/login/" id="login_form" class='form-horizontal' role='form' method="post">
	
	{% csrf_token %}

	{% for field in form %}
	<div class="form-group">
		<div class="col-sm-10 {% if field.errors or form.non_field_errors %} has-error {% endif %}">
		{% render_field field placeholder=field.label class='form-control' %}
		{% if field.errors %}
		<span class="help-block">{{ field.errors.as_text }}</span>
		{% endif %}
		{% if form.non_field_errors %}
		<span class="help-block">{{ form.non_field_errors.as_text }}</span>
		{% endif %}
		</div>
	</div>
	{% endfor %}

	<button class='btn btn-default' type="submit" name="submit">Login</button>

</form>

{% endblock %}

templates/tracker/register.html
{% extends 'tracker/base.html' %}

{% load widget_tweaks %}

{% block title %}
User Registration
{% endblock %}

{% block content %}

<h1>User Registration</h1>

<form action="/tracker/register/" class='form-horizontal' id="registration_form" role='form' method="post">
	
	{% csrf_token %}

	{% for field in form %}
	<div class="form-group">
		<div class="col-sm-10 {% if field.errors %} has-error {% endif %}">
		{% render_field field placeholder=field.label class='form-control' %}
		{% if field.errors %}
		<span class="help-block">{{ field.errors.as_text }}</span>
		{% endif %}
		</div>
	</div>
	{% endfor %}

	<button class="btn btn-default" type="submit">Register</button>

</form>

{% endblock %}